[package]
name = "cardmod-rs"
version = "0.2.0"
description = """
cardmod gives you insights into how many and of which kinds of triple triad
cards are required to yield N number of magic.
"""
edition = "2024"
rust-version = "1.91.0"

# -------------------------#
# dependencies             #
# -------------------------#
[dependencies]

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

# -------------------------#
# do you like benchmarks?  #
# -------------------------#
#[[bench]]
#name = "calculator"
#harness = false
